spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guguanjia?characterEncoding=utf8&serverTimezone=Hongkong
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  resources:
    static-locations: classpath:/,classpath:/html/


#指定到mapper包位置输出，执行SQL日志
logging:
  level:
    com:
      lyh:
        guguanjia:
          mapper: trace

server:
  servlet:
    context-path: /guguanjia

mybatis:
  configuration:
    map-underscore-to-camel-case: true

