spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guguanjia?characterEncoding=utf8&serverTimezone=Hongkong
    username: root
    password: 252090
    type: com.alibaba.druid.pool.DruidDataSource
    #druid性能监控：  1.引入starter   2.配置 使用默认springboot的starter构建的filter
    druid:
      stat-view-servlet:
        enabled: true
        login-username: druid
        login-password: 123
        url-pattern: /druid/*     #处理所有命名空间为/druid的请求
      filter:
        stat:
          enabled: true           #sql监控
        wall:
          enabled: true           #sql防火墙监控
      web-stat-filter:            #web 监控
        enabled: true
        url-pattern: /*           #监控所有请求
        exclusions: "*.js,*.jpg,*.png,*.css,/druid/*"    #默认设置了
        profile-enable: true                #开启跟踪单个uri的sql执行调用过程
        principal-session-name: loginUser
        session-stat-enable: true           #开启session监控
  resources:
    static-locations: classpath:/,classpath:/html/
  redis:
    password: 123456
    port: 6379
    lettuce:
      pool:
        min-idle: 2


#指定到mapper包位置输出，执行SQL日志
logging:
  level:
    com:
      lyh:
        guguanjia:
          mapper: trace
    org:
      springframework:
        cache: trace

server:
  servlet:
    context-path: /guguanjia

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    object-wrapper-factory: com.lyh.guguanjia.util.MapWrapperFactory


kaptcha:
  height: 32
  width: 120
  content:
    length: 4
    source: 1234567890
    space: 2
  font:
    color: black
    size: 25
  background-color:
    from: lightGray
    to: white
  border:
    enabled: true
    color: black
    thickness: 1