spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guguanjia?characterEncoding=utf8&serverTimezone=Hongkong
    username: root
    password: 252090
    type: com.alibaba.druid.pool.DruidDataSource
  resources:
    static-locations: classpath:/,classpath:/html/
  redis:
    password:
    port: 6379
    lettuce:
      pool:
        min-idle: 2


#指定到mapper包位置输出，执行SQL日志
logging:
  level:
    com:
      lyh:
        guguanjia:
          mapper: trace
    org:
      springframework:
        cache: trace

server:
  servlet:
    context-path: /guguanjia

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    object-wrapper-factory: com.lyh.guguanjia.util.MapWrapperFactory


